### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by nisi80** [matzefisi/fhem-70_SMLUSB#2]
The variable Scaler lead to a division by zero in line 298, I think because of a unintialized variable.
I already fixed this in my local repo.

**Comment by matzefisi** [comment]
Hi nisi80,

can you please provide a bit more information, or if you have already a working fix then please just raise a pull request so that I can accept you changes to my repo.

Best regards,
Matzefisi

**Comment by nisi80** [comment]
I had a crashed FHEM with the following information:

2016.02.24 17:59:26 3: Opening StromZaehler device /dev/ttyUSB0
2016.02.24 17:59:26 3: Setting StromZaehler serial parameters to 9600,8,N,1
2016.02.24 17:59:26 3: StromZaehler device opened
2016.02.24 17:59:31 1: PERL WARNING: Use of uninitialized value $scaler in division (/) at ./FHEM/70_SMLUSB.pm line 298, <GEN10> line 11.
Illegal division by zero at ./FHEM/70_SMLUSB.pm line 298, <GEN10> line 11.

After the intialization, I did not get this error any longer, but now, I see following:

2016.02.25 09:27:39 3: WARNING: unsupported character in reading Zählerstand-Bezug-Total (not A-Za-z/\d_\.-), notify the SMLUSB module maintainer.
2016.02.25 09:27:39 3: WARNING: unsupported character in reading Zählerstand-Tarif-1-Bezug (not A-Za-z/\d_\.-), notify the SMLUSB module maintainer.
2016.02.25 09:27:39 3: WARNING: unsupported character in reading Zählerstand-Tarif-2-Bezug (not A-Za-z/\d_\.-), notify the SMLUSB module maintainer.

**Comment by matzefisi** [comment]
Hi nisi80,
thanks for the additional input, this helps. I'll try to fix it until end of next week. 

One further question: Which version of FHEM are you using? 5.7?

Best regards,
Matzefisi

**Comment by nisi80** [comment]
Yes, I am using 5.7.
I will try to let your code run externally with more debug information with the rawdata.
I saw the Volkzähler project also have some cron-job running, polling the serial interface and parsing the data, but there where less OBIS-codes defined than in your project.

BTW: my HW-device is a EMH ED300L from EON/edis, which should work out of the box with your module, as I saw in the first posts in the fhem-wiki. Am I right?

**Comment by nisi80** [comment]
Found with verbose level 5 following messages several times, before something die and nor readings where made any longer:

```
2016.02.25 11:17:09 5 : SMLUSB: Partial beginning of SML File found. Repaired and start parsing
2016.02.25 11:17:11 5 : SMLUSB: End of SML found. Looking for a beginning.
2016.02.25 11:17:11 5 : SMLUSB: Started parsing
2016.02.25 11:17:11 5 : SMLUSB: SML Telegram found: 77070100010800FF
2016.02.25 11:17:11 5 : SMLUSB: Reading BulkUpdate. Value > 0
2016.02.25 11:17:11 5 : SMLUSB: SML Telegram found: 77070100010801FF
2016.02.25 11:17:11 5 : SMLUSB: SML Telegram found: 77070100010802FF
2016.02.25 11:17:11 5 : SMLUSB: Reading BulkUpdate. Value > 0
2016.02.25 11:17:11 5 : SMLUSB: SML Telegram found: 770701000F0700FF
2016.02.25 11:17:11 5 : SMLUSB: Reading BulkUpdate. Value > 0
2016.02.25 11:17:11 5 : SMLUSB: Setting state
2016.02.25 11:17:11 5 : SMLUSB: SML Telegram found: 77070100010800FF
2016.02.25 11:17:11 5 : SMLUSB: Reading BulkUpdate. Value > 0
2016.02.25 11:17:11 5 : SMLUSB: Parsing ended
```

**Comment by nisi80** [comment]
Now, I know, why my fhem and in the end also the pi dies after some minutes of operation.
The USB cable between the IR-reader and the pi was approx. 30 meters long. Way to long even with CAT6 cable, to have a stable connection. After some trials yesterday evening with a powered USB-hub, the serial connection was not readable any longer. 
Perhaps there where some bit-errors in the raw-data, lead to the strange data, without the correct scaler.
But anyway, the initialization of values, especially in usage as a divisor, need to be checked.

Sorry to bother you :-( !!!

I have to change the cabeling and will try the next steps at the end of the week.

**Comment by matzefisi** [comment]
Hi nisi, so worries. At least we fixed the devision by zero bug.

**Comment by nisi80** [comment]
Now, the SMLUSB is running fine, with the new short USB-cable :-)
